version: '3.9'
services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      # - pass
       - habit-at:/var/lib/postgresql/data
       - ./src/init_data:/docker-entrypoint-initdb.d
  web:
    image: node:lts
    user: 'node' #you can remove this if you are facing access issues when installing node packages
    working_dir: /repository
    env_file: .env
    environment:
      - NODE_ENV=development
      - TZ=America/Denver
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/repository
    command: 'npm run testandrun'
volumes:
  habit-at:
